### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by rfk**
This updates dependencies to their latest versions; in particular is pulls in the newest mozlog which should help with #8.  @jrgm r?

### CODE REVIEW

**Comment by jrgm** [comment]
In general LGTM. A couple of notes:

- bump from bluebird 2.x to bluebird 3.x - Anything to address in http://bluebirdjs.com/docs/new-in-bluebird-3.html? 

- running tests locally I see some deprecation warnings `connections property is deprecated. Use getConnections() method`, which comes from `net.Server` in node.js code, but I can't see what is triggering that call to `.connections` in our dependencies.

**Comment by jrgm** [comment]
deprecation warning also shows in https://travis-ci.org/mozilla/fxa-basket-proxy/jobs/107687028#L465. Probably harmless.

**Comment by rfk** [comment]
> Anything to address in http://bluebirdjs.com/docs/new-in-bluebird-3.html? 

Not that I can see, we make extremely limited use of bluebird in this repo.

**Comment by jrgm** [comment]
> Not that I can see, we make extremely limited use of bluebird in this repo.

Okey doke.

**Comment by rfk** [comment]
merging on the strength of "LGTM"

**Pull request merged**
