### PR TITLE
Set subscription flags when we see special utm_* parameters.

### PR DESCRIPTION
**Pull request by rfk**

### CODE REVIEW

**Comment by rfk** [comment]
OK, here's my pitch for handling https://github.com/mozilla/fxa/issues/148.  When basket gets an FxA "login" event with certain special values for `utm_campaign`, it subscribes the user to the newsletter identified in `utm_content`.  It also passes any other `utm_*` query params through in the `source_url`.

@seanmonstar could you please r? this from the code side of things.

@pmclanahan could you please check that what I'm doing makes sense here, w.r.t. the call to `/subscribe/` at https://github.com/mozilla/fxa-basket-proxy/pull/27/files#diff-708c4934bc671f6c08a782057ac08622R62

**Comment by pmac** [comment]
@rfk looks okay to me. thanks!

**Comment by seanmonstar** [comment]
looks solid to me, r+

**Comment by rfk** [comment]
FWIW, I tested this out live on https://rfkelly.dev.lcip.org, hooked up to the stage basket server.  Everything seemed to work as expected, e.g. signing in via the following URL:

  https://rfkelly.dev.lcip.org/signin?service=sync&utm_campaign=test-newsletter-campaign&utm_content=firefox-accounts-journey

Correctly resulted in my being added to the "firefox-accounts-journey" newsletter in basket.

**Pull request merged**
